import re

with open("pt/ferramentas-personalizadas.html", "r") as f:
    content = f.read()

# Replacements for PT
pt_content = content.replace(
    "<title>Ferramentas Personalizadas com IA para Atendimento Telefónico | Mobizze</title>",
    "<title>Integrações e Dados para Sistemas | Mobizze</title>"
).replace(
    '<meta name="description" content="O nosso agente de voz com IA atende chamadas, responde a perguntas, marca consultas e muito mais, com uma voz natural e baixa latência. Liberte a sua equipa do telefone.">',
    '<meta name="description" content="Conectamos os seus sistemas existentes – CRM, ERP, bases de dados e APIs – para automatizar fluxos de trabalho, eliminar duplicação de dados e acelerar a sua operação.">'
).replace(
    '<h1 class="text-xs font-mono tracking-[0.2em] uppercase mb-4 text-accent animate-fade-in-up">Os Nossos Serviços</h1>',
    '<h1 class="text-xs font-mono tracking-[0.2em] uppercase mb-4 text-accent animate-fade-in-up">Sistemas</h1>'
).replace(
    '<h2 class="font-display font-bold text-dark leading-[1.1] tracking-tight mb-6 animate-fade-in-up delay-100" style="font-size: clamp(2.5rem, 5vw, 4rem);">\n                        Software à Medida: <span class="text-accent">Aplicações e Dashboards</span> Inteligentes.\n                    </h2>',
    '<h2 class="font-display font-bold text-dark leading-[1.1] tracking-tight mb-6 animate-fade-in-up delay-100" style="font-size: clamp(2.5rem, 5vw, 4rem);">\n                        Conecte as suas <span class="text-accent">Ferramentas</span>. Unifique os seus <span class="text-accent">Dados</span>.\n                    </h2>'
).replace(
    '<p class="text-lg text-slate-600 leading-relaxed max-w-2xl mx-auto animate-fade-in-up delay-200">\n                        Desenvolvemos ferramentas internas, portais de clientes e dashboards personalizados infundidos com IA, desenhados para resolver os desafios únicos do seu negócio quando as soluções "prontas a usar" não são suficientes.\n                    </p>',
    '<p class="text-lg text-slate-600 leading-relaxed max-w-2xl mx-auto animate-fade-in-up delay-200">\n                        Eliminamos os silos de informação. Integramos CRMs, ERPs e aplicações isoladas para criar fluxos de trabalho contínuos e automatizados.\n                    </p>'
).replace(
    '<h2 class="text-3xl font-display font-bold text-dark tracking-tight text-center mb-16 reveal">Software desenhado para a sua <span class="text-accent">Operação</span>.</h2>',
    '<h2 class="text-3xl font-display font-bold text-dark tracking-tight text-center mb-16 reveal">O Fim do <span class="text-accent">Trabalho Manual</span> Repetitivo.</h2>'
).replace(
    '<svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="3" y1="9" x2="21" y2="9"></line><line x1="9" y1="21" x2="9" y2="9"></line></svg>\n                        </div>\n                        <h4 class="font-display font-bold text-dark text-lg">Dashboards de Dados</h4>\n                        <p class="text-sm text-slate-600 leading-relaxed">Centralize os dados da sua empresa num único local. Dashboards interativos e em tempo real que ajudam a tomar decisões mais rápidas.</p>',
    '<svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>\n                        </div>\n                        <h4 class="font-display font-bold text-dark text-lg">Integração de CRMs e ERPs</h4>\n                        <p class="text-sm text-slate-600 leading-relaxed">Conectamos o seu software de gestão (ex: Salesforce, Hubspot, Primavera) a outras plataformas para manter a informação sempre sincronizada.</p>'
).replace(
    '<svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>\n                        </div>\n                        <h4 class="font-display font-bold text-dark text-lg">Portais de Clientes</h4>\n                        <p class="text-sm text-slate-600 leading-relaxed">Ofereça aos seus clientes acesso seguro a documentos, relatórios e processos, melhorando a transparência e retenção.</p>',
    '<svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"></polyline></svg>\n                        </div>\n                        <h4 class="font-display font-bold text-dark text-lg">Fluxos de Dados (ETL)</h4>\n                        <p class="text-sm text-slate-600 leading-relaxed">Extraímos, transformamos e carregamos dados de múltiplas fontes para a sua base de dados central, garantindo qualidade e consistência.</p>'
).replace(
    '<svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="16 18 22 12 16 6"></polyline><polyline points="8 6 2 12 8 18"></polyline></svg>\n                        </div>\n                        <h4 class="font-display font-bold text-dark text-lg">Sistemas Internos</h4>\n                        <p class="text-sm text-slate-600 leading-relaxed">Construímos aplicações internas desenhadas especificamente para simplificar e digitalizar os processos operacionais da sua equipa.</p>',
    '<svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="2" width="20" height="8" rx="2" ry="2"></rect><rect x="2" y="14" width="20" height="8" rx="2" ry="2"></rect><line x1="6" y1="6" x2="6.01" y2="6"></line><line x1="6" y1="18" x2="6.01" y2="18"></line></svg>\n                        </div>\n                        <h4 class="font-display font-bold text-dark text-lg">Desenvolvimento de APIs</h4>\n                        <p class="text-sm text-slate-600 leading-relaxed">Criamos APIs RESTful ou GraphQL para permitir que sistemas antigos comuniquem com aplicações modernas em tempo real.</p>'
).replace(
    '<svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>\n                        </div>\n                        <h4 class="font-display font-bold text-dark text-lg">IA Incorporada</h4>\n                        <p class="text-sm text-slate-600 leading-relaxed">Infundimos modelos de linguagem (LLMs) nas suas ferramentas para gerar relatórios, analisar documentos ou apoiar decisões automaticamente.</p>',
    '<svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"></path><polyline points="3.27 6.96 12 12.01 20.73 6.96"></polyline><line x1="12" y1="22.08" x2="12" y2="12"></line></svg>\n                        </div>\n                        <h4 class="font-display font-bold text-dark text-lg">Automação de Tarefas</h4>\n                        <p class="text-sm text-slate-600 leading-relaxed">Substituímos o "copiar e colar" manual por workflows automáticos (via webhooks, Zapier, Make, ou código customizado).</p>'
).replace(
    '<h2 class="text-3xl font-display font-bold text-dark tracking-tight text-center mb-16 reveal">O Nosso Processo de Desenvolvimento</h2>',
    '<h2 class="text-3xl font-display font-bold text-dark tracking-tight text-center mb-16 reveal">O Nosso Processo de Integração</h2>'
).replace(
    '<h3 class="text-lg font-display font-bold text-dark mb-2">Levantamento</h3>\n                        <p class="text-sm text-slate-600 leading-relaxed">Analisamos a sua necessidade técnica, desenhamos a arquitetura do sistema e definimos o plano de implementação e tecnologias.</p>',
    '<h3 class="text-lg font-display font-bold text-dark mb-2">Mapeamento</h3>\n                        <p class="text-sm text-slate-600 leading-relaxed">Avaliamos os sistemas que utiliza atualmente e mapeamos o fluxo ideal da informação entre eles.</p>'
).replace(
    '<h3 class="text-lg font-display font-bold text-dark mb-2">Prototipagem</h3>\n                        <p class="text-sm text-slate-600 leading-relaxed">Desenhamos a interface e a experiência de utilizador (UI/UX) para que valide visualmente a solução antes da programação.</p>',
    '<h3 class="text-lg font-display font-bold text-dark mb-2">Design da Arquitetura</h3>\n                        <p class="text-sm text-slate-600 leading-relaxed">Definimos a arquitetura técnica, escolhendo as APIs, webhooks ou middlewares necessários para a integração.</p>'
).replace(
    '<h3 class="text-lg font-display font-bold text-dark mb-2">Construção</h3>\n                        <p class="text-sm text-slate-600 leading-relaxed">Desenvolvemos o software de forma ágil, com integrações robustas e garantindo total segurança dos dados da sua empresa.</p>',
    '<h3 class="text-lg font-display font-bold text-dark mb-2">Desenvolvimento</h3>\n                        <p class="text-sm text-slate-600 leading-relaxed">Programamos as conexões, garantindo o tratamento de erros, segurança dos dados e escalabilidade do fluxo.</p>'
).replace(
    '<h3 class="text-lg font-display font-bold text-dark mb-2">Entrega e Suporte</h3>\n                        <p class="text-sm text-slate-600 leading-relaxed">Lançamos a ferramenta em produção, damos formação à sua equipa e garantimos manutenção para evolução contínua.</p>',
    '<h3 class="text-lg font-display font-bold text-dark mb-2">Testes & Lançamento</h3>\n                        <p class="text-sm text-slate-600 leading-relaxed">Testamos extensivamente em ambiente seguro antes de ativar as integrações na sua operação diária.</p>'
).replace(
    '<h2 class="font-display font-bold text-white" style="font-size: clamp(2.5rem, 5vw, 3.5rem); line-height: 1.1;">\n                    Precisa de uma Solução à Medida?\n                </h2>\n                <p class="max-w-xl mx-auto mt-6 text-lg text-slate-300 leading-relaxed">\n                    Marque uma reunião técnica gratuita. Vamos analisar a sua arquitetura atual e perceber como uma ferramenta personalizada pode escalar a sua operação.\n                </p>\n                <div class="mt-10">\n                    <a href="contacto.html" class="inline-flex items-center justify-center gap-2 px-8 py-4 rounded-full text-sm font-bold transition-all duration-300 bg-accent text-white shadow-lg shadow-blue-500/30 hover:bg-blue-700 hover:-translate-y-1 hover:shadow-xl hover:shadow-blue-500/40">\n                        Pedir diagnóstico gratuito\n                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14m-7-7l7 7l-7 7"/></svg>\n                    </a>\n                </div>',
    '<h2 class="font-display font-bold text-white" style="font-size: clamp(2.5rem, 5vw, 3.5rem); line-height: 1.1;">\n                    Pronto para Conectar a sua Operação?\n                </h2>\n                <p class="max-w-xl mx-auto mt-6 text-lg text-slate-300 leading-relaxed">\n                    Marque uma reunião técnica gratuita. Vamos analisar a sua arquitetura atual e propor a melhor forma de integrar os seus sistemas.\n                </p>\n                <div class="mt-10">\n                    <a href="contacto.html" class="inline-flex items-center justify-center gap-2 px-8 py-4 rounded-full text-sm font-bold transition-all duration-300 bg-accent text-white shadow-lg shadow-blue-500/30 hover:bg-blue-700 hover:-translate-y-1 hover:shadow-xl hover:shadow-blue-500/40">\n                        Falar com um Arquiteto de Software\n                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14m-7-7l7 7l-7 7"/></svg>\n                    </a>\n                </div>'
)

with open("pt/integracoes.html", "w") as f:
    f.write(pt_content)

# Now do EN
with open("en/custom-tools.html", "r") as f:
    en_content = f.read()

en_content = en_content.replace(
    "<title>Custom Software & Internal Tools | Mobizze</title>",
    "<title>Data & System Integrations | Mobizze</title>"
).replace(
    '<meta name="description" content="We develop custom software, data dashboards, client portals, and internal systems to solve your business\'s unique challenges. Scalable, secure, and AI-ready.">',
    '<meta name="description" content="We connect your existing systems – CRM, ERP, databases, and APIs – to automate workflows, eliminate data duplication, and accelerate your operations.">'
).replace(
    '<h1 class="text-xs font-mono tracking-[0.2em] uppercase mb-4 text-accent animate-fade-in-up">Development</h1>',
    '<h1 class="text-xs font-mono tracking-[0.2em] uppercase mb-4 text-accent animate-fade-in-up">Systems</h1>'
).replace(
    '<h2 class="font-display font-bold text-dark leading-[1.1] tracking-tight mb-6 animate-fade-in-up delay-100" style="font-size: clamp(2.5rem, 5vw, 4rem);">\n                        Custom <span class="text-accent">Software</span> for Unique Challenges.\n                    </h2>',
    '<h2 class="font-display font-bold text-dark leading-[1.1] tracking-tight mb-6 animate-fade-in-up delay-100" style="font-size: clamp(2.5rem, 5vw, 4rem);">\n                        Connect your <span class="text-accent">Tools</span>. Unify your <span class="text-accent">Data</span>.\n                    </h2>'
).replace(
    '<p class="text-lg text-slate-600 leading-relaxed max-w-2xl mx-auto animate-fade-in-up delay-200">\n                        We build robust applications, intelligent dashboards, and internal portals perfectly tailored to your company\'s processes and specific needs.\n                    </p>',
    '<p class="text-lg text-slate-600 leading-relaxed max-w-2xl mx-auto animate-fade-in-up delay-200">\n                        We eliminate information silos. We integrate CRMs, ERPs, and isolated applications to create seamless, automated workflows.\n                    </p>'
).replace(
    '<h2 class="text-3xl font-display font-bold text-dark tracking-tight text-center mb-16 reveal">Solutions that <span class="text-accent">Scale with You</span>.</h2>',
    '<h2 class="text-3xl font-display font-bold text-dark tracking-tight text-center mb-16 reveal">The End of <span class="text-accent">Repetitive</span> Manual Work.</h2>'
).replace(
    '<svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"></path><polyline points="3.27 6.96 12 12.01 20.73 6.96"></polyline><line x1="12" y1="22.08" x2="12" y2="12"></line></svg>\n                        </div>\n                        <h4 class="font-display font-bold text-dark text-lg">Internal Systems</h4>\n                        <p class="text-sm text-slate-600 leading-relaxed">Replace messy spreadsheets and scattered tools with a unified platform built exactly for how your team works.</p>',
    '<svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>\n                        </div>\n                        <h4 class="font-display font-bold text-dark text-lg">CRM & ERP Integration</h4>\n                        <p class="text-sm text-slate-600 leading-relaxed">We connect your management software (e.g. Salesforce, Hubspot, Primavera) to other platforms to keep information synced.</p>'
).replace(
    '<svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="3" y1="9" x2="21" y2="9"></line><line x1="9" y1="21" x2="9" y2="9"></line></svg>\n                        </div>\n                        <h4 class="font-display font-bold text-dark text-lg">Data Dashboards</h4>\n                        <p class="text-sm text-slate-600 leading-relaxed">Centralize your metrics. We build real-time visual dashboards so you can make decisions based on clear, consolidated data.</p>',
    '<svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"></polyline></svg>\n                        </div>\n                        <h4 class="font-display font-bold text-dark text-lg">Data Flows (ETL)</h4>\n                        <p class="text-sm text-slate-600 leading-relaxed">We extract, transform, and load data from multiple sources into your central database, ensuring quality and consistency.</p>'
).replace(
    '<svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>\n                        </div>\n                        <h4 class="font-display font-bold text-dark text-lg">Client Portals</h4>\n                        <p class="text-sm text-slate-600 leading-relaxed">Offer a premium experience to your clients with secure portals for document sharing, progress tracking, and communication.</p>',
    '<svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="2" width="20" height="8" rx="2" ry="2"></rect><rect x="2" y="14" width="20" height="8" rx="2" ry="2"></rect><line x1="6" y1="6" x2="6.01" y2="6"></line><line x1="6" y1="18" x2="6.01" y2="18"></line></svg>\n                        </div>\n                        <h4 class="font-display font-bold text-dark text-lg">API Development</h4>\n                        <p class="text-sm text-slate-600 leading-relaxed">We create RESTful or GraphQL APIs to allow legacy systems to communicate with modern applications in real-time.</p>'
).replace(
    '<svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path></svg>\n                        </div>\n                        <h4 class="font-display font-bold text-dark text-lg">Embedded AI</h4>\n                        <p class="text-sm text-slate-600 leading-relaxed">We integrate artificial intelligence directly into your custom software to automate tasks, analyze text, or generate insights.</p>',
    '<svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"></path><polyline points="3.27 6.96 12 12.01 20.73 6.96"></polyline><line x1="12" y1="22.08" x2="12" y2="12"></line></svg>\n                        </div>\n                        <h4 class="font-display font-bold text-dark text-lg">Task Automation</h4>\n                        <p class="text-sm text-slate-600 leading-relaxed">We replace manual "copy-pasting" with automated workflows (via webhooks, Zapier, Make, or custom code).</p>'
).replace(
    '<h2 class="text-3xl font-display font-bold text-dark tracking-tight text-center mb-16 reveal">Our Development Process</h2>',
    '<h2 class="text-3xl font-display font-bold text-dark tracking-tight text-center mb-16 reveal">Our Integration Process</h2>'
).replace(
    '<h3 class="text-lg font-display font-bold text-dark mb-2">Discovery</h3>\n                        <p class="text-sm text-slate-600 leading-relaxed">We deeply understand your business problem, map out requirements, and define the technical architecture.</p>',
    '<h3 class="text-lg font-display font-bold text-dark mb-2">Mapping</h3>\n                        <p class="text-sm text-slate-600 leading-relaxed">We evaluate the systems you currently use and map out the ideal flow of information between them.</p>'
).replace(
    '<h3 class="text-lg font-display font-bold text-dark mb-2">Prototyping</h3>\n                        <p class="text-sm text-slate-600 leading-relaxed">We create high-fidelity visual prototypes so you can test the interface and user experience before we write code.</p>',
    '<h3 class="text-lg font-display font-bold text-dark mb-2">Architecture Design</h3>\n                        <p class="text-sm text-slate-600 leading-relaxed">We define the technical architecture, choosing the APIs, webhooks, or middleware needed for the integration.</p>'
).replace(
    '<h3 class="text-lg font-display font-bold text-dark mb-2">Development</h3>\n                        <p class="text-sm text-slate-600 leading-relaxed">We build the software using modern, secure, and scalable technologies, with frequent updates on progress.</p>',
    '<h3 class="text-lg font-display font-bold text-dark mb-2">Development</h3>\n                        <p class="text-sm text-slate-600 leading-relaxed">We program the connections, ensuring robust error handling, data security, and workflow scalability.</p>'
).replace(
    '<h3 class="text-lg font-display font-bold text-dark mb-2">Delivery & Support</h3>\n                        <p class="text-sm text-slate-600 leading-relaxed">We launch the platform, train your team, and provide continuous support to ensure everything runs smoothly.</p>',
    '<h3 class="text-lg font-display font-bold text-dark mb-2">Testing & Launch</h3>\n                        <p class="text-sm text-slate-600 leading-relaxed">We test extensively in a secure environment before activating the integrations in your daily operations.</p>'
).replace(
    '<h2 class="font-display font-bold text-white" style="font-size: clamp(2.5rem, 5vw, 3.5rem); line-height: 1.1;">\n                    Let\'s Build Your Ideal Solution?\n                </h2>\n                <p class="max-w-xl mx-auto mt-6 text-lg text-slate-300 leading-relaxed">\n                    Schedule a free technical meeting to discuss your challenge. We will evaluate feasibility and propose the best architecture.\n                </p>\n                <div class="mt-10">\n                    <a href="contact.html" class="inline-flex items-center justify-center gap-2 px-8 py-4 rounded-full text-sm font-bold transition-all duration-300 bg-accent text-white shadow-lg shadow-blue-500/30 hover:bg-blue-700 hover:-translate-y-1 hover:shadow-xl hover:shadow-blue-500/40">\n                        Talk to an Engineer\n                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14m-7-7l7 7l-7 7"/></svg>\n                    </a>\n                </div>',
    '<h2 class="font-display font-bold text-white" style="font-size: clamp(2.5rem, 5vw, 3.5rem); line-height: 1.1;">\n                    Ready to Connect Your Operations?\n                </h2>\n                <p class="max-w-xl mx-auto mt-6 text-lg text-slate-300 leading-relaxed">\n                    Schedule a free technical meeting. We will analyze your current architecture and propose the best way to integrate your systems.\n                </p>\n                <div class="mt-10">\n                    <a href="contact.html" class="inline-flex items-center justify-center gap-2 px-8 py-4 rounded-full text-sm font-bold transition-all duration-300 bg-accent text-white shadow-lg shadow-blue-500/30 hover:bg-blue-700 hover:-translate-y-1 hover:shadow-xl hover:shadow-blue-500/40">\n                        Talk to a Software Architect\n                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14m-7-7l7 7l-7 7"/></svg>\n                    </a>\n                </div>'
)

with open("en/integrations.html", "w") as f:
    f.write(en_content)

print("Done")
